### ISSUE TITLE
script fails to run with 'syntax error'

### ISSUE THREAD

**Issue by fuxxociety** [gdelugre/ida-arm-system-highlight#8]
Windows 10 64-bit
IDA Pro v7.3.190614
Python 2.7.18 & 3.10.5 installed. IDA 7.3 is only capable of Python2.7.

When running the script, the script halts with the error
`C:\Users\<redacted>\AppData\Roaming\Hex-Rays\IDA Pro\Scripts\highlight_arm_system_insn.py: invalid syntax (C:/Users/<redacted>/AppData/Roaming/Hex-Rays/IDA Pro/Scripts/highlight_arm_system_insn.py, line 61)
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.3\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Users/<redacted>/AppData/Roaming/Hex-Rays/IDA Pro/Scripts/highlight_arm_system_insn.py", line 61
    *SYSTEM_CALL_INSN,
    ^
SyntaxError: invalid syntax`

It appears this script is not designed for or compatible with Python2.7. I can accept that, but mainly wanted to make others aware of the limitation. I assume to run this script you will need IDA>=7.4, which to my knowledge is the first version that was capable of utilizing Python3.

For sake of completeness, I tried running the script in my Python3 console to see what would happen. I was presented with a different error:
`stem_insn.py", line 11, in <module>
    from idc import *
ModuleNotFoundError: No module named 'idc'`

This would be expected, as the raw Python3 environment would not have the idapython libs provided by IDA>=7.4

**Comment by fuxxociety** [comment]
Closing this issue. A backport is not being requested.
